CREATE TABLE products (
    product_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    product_name VARCHAR(200) NOT NULL,
    description TEXT,
    category VARCHAR(100),

    unit VARCHAR(20) DEFAULT 'meter',

    cost_price NUMERIC(10,2),
    selling_price NUMERIC(10,2) NOT NULL,

    stock_quantity NUMERIC(10,2) DEFAULT 0,
    min_stock_level NUMERIC(10,2) DEFAULT 0,

    is_active BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE products
ADD CONSTRAINT fk_products_category
FOREIGN KEY (category)
REFERENCES product_category(category_name);

INSERT INTO product_category (category_name, is_online) VALUES
('Lining', TRUE),
('Fancy Fabric', TRUE),
('Dress Suits', TRUE),
('Cotton Fabric', TRUE),
('Handloom Fabrics', TRUE);


CREATE TABLE product_category (
    category_name VARCHAR(100) PRIMARY KEY,
    is_online BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE products
ADD CONSTRAINT fk_category_name
FOREIGN KEY (category_name)
REFERENCES product_category(category_name);

ALTER TABLE products ALTER COLUMN product_id SET GENERATED BY DEFAULT;