-- Wholesale module V10: wholesale inventory ledger, stock adjustments and inventory settings.
-- Wholesale stock only (wholesale_products.available_quantity). Retail products/stock are never read or changed.
--
-- Every change to wholesale stock is written to wholesale_inventory_ledger in the same transaction, with its source
-- document (purchase, sales document, stock adjustment). Ledger rows are append-only: mistakes are corrected with
-- REVERSAL or ADJUSTMENT rows, never by editing history.

-- ── Settings ─────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wholesale_inventory_settings (
    settings_id          SMALLINT     PRIMARY KEY DEFAULT 1,
    allow_negative_stock BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_by           VARCHAR(100),
    CONSTRAINT ck_wholesale_inventory_settings_singleton CHECK (settings_id = 1)
);
INSERT INTO wholesale_inventory_settings (settings_id, allow_negative_stock) VALUES (1, FALSE)
ON CONFLICT (settings_id) DO NOTHING;

-- Negative stock is now a business setting (enforced by the inventory service), so the hard DB rule goes.
ALTER TABLE wholesale_products DROP CONSTRAINT IF EXISTS ck_wholesale_products_qty;

-- ── Wholesale purchases are cancelled, not deleted, so their ledger rows keep a source document ───
ALTER TABLE wholesale_purchases ADD COLUMN IF NOT EXISTS status        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE wholesale_purchases ADD COLUMN IF NOT EXISTS cancelled_at  TIMESTAMP;
ALTER TABLE wholesale_purchases ADD COLUMN IF NOT EXISTS cancelled_by  VARCHAR(100);
ALTER TABLE wholesale_purchases ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(255);
ALTER TABLE wholesale_purchases ADD COLUMN IF NOT EXISTS created_by    VARCHAR(100);
ALTER TABLE wholesale_purchases DROP CONSTRAINT IF EXISTS ck_wholesale_purchases_cancel_status;
ALTER TABLE wholesale_purchases ADD CONSTRAINT ck_wholesale_purchases_cancel_status CHECK (status IN ('ACTIVE', 'CANCELLED'));
-- A cancelled supplier invoice may be entered again.
DROP INDEX IF EXISTS uq_wholesale_purchases_supplier_invoice;
CREATE UNIQUE INDEX IF NOT EXISTS uq_wholesale_purchases_supplier_invoice
    ON wholesale_purchases (supplier_id, LOWER(invoice_number)) WHERE status = 'ACTIVE';

-- ── Stock adjustments (source document for manual corrections and the opening balance) ─────────
ALTER TABLE wholesale_document_settings DROP CONSTRAINT IF EXISTS ck_wholesale_doc_settings_type;
ALTER TABLE wholesale_document_settings ADD CONSTRAINT ck_wholesale_doc_settings_type
    CHECK (doc_type IN ('QUOTATION', 'SALES_RECEIPT', 'CREDIT_NOTE', 'DEBIT_NOTE', 'STOCK_ADJUSTMENT'));
INSERT INTO wholesale_document_settings (doc_type, prefix, separator, include_financial_year, reset_each_financial_year,
        number_padding, display_label, print_title, gst_classification, value_effect, stock_effect, reference_mode,
        allowed_reference_types, reason_required)
VALUES ('STOCK_ADJUSTMENT', 'ADJ', '-', FALSE, FALSE, 6, 'Stock Adjustment', 'STOCK ADJUSTMENT', 'OTHER', 'CHARGE',
        'NONE', 'NONE', '', TRUE)
ON CONFLICT (doc_type) DO NOTHING;

CREATE TABLE IF NOT EXISTS wholesale_stock_adjustments (
    adjustment_id     INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_number VARCHAR(40)  NOT NULL UNIQUE,
    adjustment_date   DATE         NOT NULL,
    reason            VARCHAR(500) NOT NULL,
    is_opening        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    created_by        VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS wholesale_stock_adjustment_items (
    adjustment_item_id   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_id        INTEGER       NOT NULL REFERENCES wholesale_stock_adjustments (adjustment_id) ON DELETE CASCADE,
    wholesale_product_id INTEGER       NOT NULL REFERENCES wholesale_products (wholesale_product_id),
    quantity_change      NUMERIC(12,3) NOT NULL,
    notes                VARCHAR(255),
    CONSTRAINT ck_wholesale_stock_adj_items_nonzero CHECK (quantity_change <> 0)
);

CREATE INDEX IF NOT EXISTS idx_wholesale_stock_adj_items_adj ON wholesale_stock_adjustment_items (adjustment_id);

-- ── Ledger ───────────────────────────────────────────────────────────────────────────────────────
-- transaction_type: OPENING, PURCHASE, SALE, CREDIT, DEBIT, RETURN, ADJUSTMENT, REVERSAL
-- reference_type  : PURCHASE (wholesale_purchases), SALES_RECEIPT / CREDIT_NOTE / DEBIT_NOTE
--                   (wholesale_sales_documents), STOCK_ADJUSTMENT (wholesale_stock_adjustments)
-- balance_quantity: product stock right after this row was posted (posting order = ledger_id order).
CREATE TABLE IF NOT EXISTS wholesale_inventory_ledger (
    ledger_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wholesale_product_id INTEGER       NOT NULL REFERENCES wholesale_products (wholesale_product_id),
    transaction_type     VARCHAR(20)   NOT NULL,
    reference_type       VARCHAR(20)   NOT NULL,
    reference_id         INTEGER       NOT NULL,
    reference_number     VARCHAR(60),
    reverses_ledger_id   BIGINT        REFERENCES wholesale_inventory_ledger (ledger_id),
    quantity_in          NUMERIC(12,3) NOT NULL DEFAULT 0,
    quantity_out         NUMERIC(12,3) NOT NULL DEFAULT 0,
    balance_quantity     NUMERIC(12,3) NOT NULL,
    unit                 VARCHAR(20)   NOT NULL,
    rate                 NUMERIC(12,2),
    transaction_date     DATE          NOT NULL,
    notes                VARCHAR(255),
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    created_by           VARCHAR(100),
    CONSTRAINT ck_wholesale_inv_ledger_type CHECK (transaction_type IN
        ('OPENING', 'PURCHASE', 'SALE', 'CREDIT', 'DEBIT', 'RETURN', 'ADJUSTMENT', 'REVERSAL')),
    CONSTRAINT ck_wholesale_inv_ledger_ref CHECK (reference_type IN
        ('PURCHASE', 'SALES_RECEIPT', 'CREDIT_NOTE', 'DEBIT_NOTE', 'STOCK_ADJUSTMENT')),
    CONSTRAINT ck_wholesale_inv_ledger_qty CHECK (quantity_in >= 0 AND quantity_out >= 0 AND ((quantity_in > 0) <> (quantity_out > 0)))
);

CREATE INDEX IF NOT EXISTS idx_wholesale_inv_ledger_product ON wholesale_inventory_ledger (wholesale_product_id, ledger_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_inv_ledger_ref ON wholesale_inventory_ledger (reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_inv_ledger_date ON wholesale_inventory_ledger (transaction_date);
-- A ledger row can be reversed only once.
CREATE UNIQUE INDEX IF NOT EXISTS uq_wholesale_inv_ledger_reverses ON wholesale_inventory_ledger (reverses_ledger_id)
    WHERE reverses_ledger_id IS NOT NULL;

-- ── Opening balance ──────────────────────────────────────────────────────────────────────────────
-- Stock that existed before the ledger is recorded once as an OPENING adjustment, so every product's ledger starts
-- from a source document and sums to its current quantity.
INSERT INTO wholesale_stock_adjustments (adjustment_number, adjustment_date, reason, is_opening, created_by)
SELECT 'OPENING', CURRENT_DATE, 'Opening balance when the wholesale stock ledger started', TRUE, 'SYSTEM'
 WHERE EXISTS (SELECT 1 FROM wholesale_products WHERE available_quantity <> 0)
   AND NOT EXISTS (SELECT 1 FROM wholesale_stock_adjustments WHERE adjustment_number = 'OPENING');

INSERT INTO wholesale_stock_adjustment_items (adjustment_id, wholesale_product_id, quantity_change)
SELECT a.adjustment_id, p.wholesale_product_id, p.available_quantity
  FROM wholesale_products p
  JOIN wholesale_stock_adjustments a ON a.adjustment_number = 'OPENING'
 WHERE p.available_quantity <> 0
   AND NOT EXISTS (SELECT 1 FROM wholesale_stock_adjustment_items i
                    WHERE i.adjustment_id = a.adjustment_id AND i.wholesale_product_id = p.wholesale_product_id);

INSERT INTO wholesale_inventory_ledger (wholesale_product_id, transaction_type, reference_type, reference_id,
        reference_number, quantity_in, quantity_out, balance_quantity, unit, rate, transaction_date, notes, created_by)
SELECT p.wholesale_product_id, 'OPENING', 'STOCK_ADJUSTMENT', a.adjustment_id, a.adjustment_number,
       GREATEST(p.available_quantity, 0), GREATEST(-p.available_quantity, 0), p.available_quantity, p.unit,
       p.purchase_rate, CURRENT_DATE, 'Stock on hand when the ledger started', 'SYSTEM'
  FROM wholesale_products p
  JOIN wholesale_stock_adjustments a ON a.adjustment_number = 'OPENING'
 WHERE p.available_quantity <> 0
   AND NOT EXISTS (SELECT 1 FROM wholesale_inventory_ledger l WHERE l.wholesale_product_id = p.wholesale_product_id);
