-- Wholesale module V11: Instagram customer messaging (webhook inbox, conversations, AI auto-replies, human takeover).
-- Wholesale only. Nothing in the retail chatbot / WhatsApp / Instagram Reels features is read or changed.
--
-- The AI never writes business data: it only reads wholesale products / price rules / stock through backend services,
-- and every inbound + outbound message is stored here with the intent, the business facts used and the reply.

-- ── Settings (single row; secrets are write-only through the API) ───────────────────────────────
CREATE TABLE IF NOT EXISTS wholesale_instagram_settings (
    settings_id          SMALLINT      PRIMARY KEY DEFAULT 1,
    is_enabled           BOOLEAN       NOT NULL DEFAULT FALSE,   -- receive messages at all
    auto_reply_enabled   BOOLEAN       NOT NULL DEFAULT TRUE,    -- AI replies (per conversation it can still be off)
    instagram_account_id VARCHAR(64),                            -- professional account id (webhook entry.id)
    api_base_url         VARCHAR(255)  NOT NULL DEFAULT 'https://graph.facebook.com/v21.0',
    access_token         TEXT,                                   -- page / Instagram user access token
    app_secret           VARCHAR(255),                           -- verifies X-Hub-Signature-256
    verify_token         VARCHAR(255),                           -- webhook subscription handshake
    share_stock_quantity BOOLEAN       NOT NULL DEFAULT FALSE,   -- false: say "available", never the exact quantity
    handoff_message      VARCHAR(500)  NOT NULL DEFAULT 'Thank you for your message. Our team will get back to you shortly.',
    updated_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_by           VARCHAR(100),
    CONSTRAINT ck_wholesale_instagram_settings_singleton CHECK (settings_id = 1)
);
INSERT INTO wholesale_instagram_settings (settings_id) VALUES (1) ON CONFLICT (settings_id) DO NOTHING;

-- ── Conversations: one per Instagram user (IGSID) ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wholesale_ig_conversations (
    conversation_id       INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instagram_user_id     VARCHAR(64)  NOT NULL UNIQUE,          -- Instagram-scoped user id of the customer
    instagram_username    VARCHAR(100),
    display_name          VARCHAR(200),
    wholesale_customer_id INTEGER      REFERENCES wholesale_customers (wholesale_customer_id) ON DELETE SET NULL,
    ai_enabled            BOOLEAN      NOT NULL DEFAULT TRUE,    -- false = human takeover
    takeover_by           VARCHAR(100),
    takeover_at           TIMESTAMP,
    needs_attention       BOOLEAN      NOT NULL DEFAULT FALSE,
    attention_reason      VARCHAR(255),
    unread_count          INTEGER      NOT NULL DEFAULT 0,
    last_product_id       INTEGER      REFERENCES wholesale_products (wholesale_product_id) ON DELETE SET NULL,
    last_message_text     VARCHAR(300),
    last_message_at       TIMESTAMP,
    last_inbound_at       TIMESTAMP,                             -- start of Instagram's 24-hour reply window
    created_at            TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_wholesale_ig_conversations_last ON wholesale_ig_conversations (last_message_at DESC);
CREATE INDEX IF NOT EXISTS ix_wholesale_ig_conversations_customer ON wholesale_ig_conversations (wholesale_customer_id);

-- ── Messages: full history, both directions ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS wholesale_ig_messages (
    message_id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id      INTEGER      NOT NULL REFERENCES wholesale_ig_conversations (conversation_id) ON DELETE CASCADE,
    instagram_message_id VARCHAR(255),                           -- Meta "mid"; dedupes webhook retries / echoes
    direction            VARCHAR(10)  NOT NULL,                  -- INBOUND | OUTBOUND
    sender_type          VARCHAR(10)  NOT NULL,                  -- CUSTOMER | AI | STAFF
    message_text         TEXT,
    attachments          JSONB,
    intent               VARCHAR(40),                            -- inbound: understood intent
    extracted            JSONB,                                  -- inbound: product / quantity / unit the AI extracted
    facts                JSONB,                                  -- inbound: business data the reply was built from
    ai_response          TEXT,                                   -- inbound: reply generated for this message
    reply_message_id     BIGINT,                                 -- inbound: the outbound message that answered it
    status               VARCHAR(20)  NOT NULL,
    error_message        VARCHAR(1000),
    sent_by              VARCHAR(100),                           -- staff username for STAFF messages
    message_at           TIMESTAMP    NOT NULL,                  -- Instagram timestamp (inbound) / send time (outbound)
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_wholesale_ig_messages_direction CHECK (direction IN ('INBOUND', 'OUTBOUND')),
    CONSTRAINT ck_wholesale_ig_messages_sender CHECK (sender_type IN ('CUSTOMER', 'AI', 'STAFF')),
    CONSTRAINT ck_wholesale_ig_messages_status CHECK (status IN (
        'RECEIVED', 'PROCESSING', 'REPLIED', 'NEEDS_HUMAN', 'HUMAN_TAKEOVER', 'AI_DISABLED', 'IGNORED', 'FAILED',
        'PENDING', 'SENT'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_wholesale_ig_messages_mid
    ON wholesale_ig_messages (instagram_message_id) WHERE instagram_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_wholesale_ig_messages_conversation ON wholesale_ig_messages (conversation_id, message_at, message_id);
