-- Wholesale module V1: wholesale product master + wholesale purchase bills.
-- Runs inside each firm schema (search_path is set by WholesaleSchemaInitializer).
-- Adds NEW tables only. No retail table is altered. The only references to retail
-- tables are read-only foreign keys to suppliers(supplier_id).

CREATE TABLE IF NOT EXISTS wholesale_products (
    wholesale_product_id INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code         VARCHAR(50),
    product_name         VARCHAR(200)  NOT NULL,
    product_type         VARCHAR(100),
    hsn_code             VARCHAR(8),
    description          TEXT,
    unit                 VARCHAR(20)   NOT NULL DEFAULT 'Pieces',
    available_quantity   NUMERIC(12,3) NOT NULL DEFAULT 0,
    purchase_rate        NUMERIC(12,2) NOT NULL DEFAULT 0,
    gst_pct              NUMERIC(5,2)  NOT NULL DEFAULT 5,
    supplier_id          INTEGER       REFERENCES suppliers (supplier_id) ON DELETE SET NULL,
    is_active            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_wholesale_products_qty  CHECK (available_quantity >= 0),
    CONSTRAINT ck_wholesale_products_rate CHECK (purchase_rate >= 0),
    CONSTRAINT ck_wholesale_products_gst  CHECK (gst_pct >= 0 AND gst_pct <= 100)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wholesale_products_code
    ON wholesale_products (LOWER(product_code)) WHERE product_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_wholesale_products_name
    ON wholesale_products (LOWER(product_name));

CREATE TABLE IF NOT EXISTS wholesale_product_images (
    image_id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wholesale_product_id INTEGER      NOT NULL REFERENCES wholesale_products (wholesale_product_id) ON DELETE CASCADE,
    image_url            VARCHAR(500) NOT NULL,
    public_id            VARCHAR(255),
    sort_order           INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wholesale_product_images_product
    ON wholesale_product_images (wholesale_product_id, sort_order);

CREATE TABLE IF NOT EXISTS wholesale_purchases (
    wholesale_purchase_id INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id           INTEGER       NOT NULL REFERENCES suppliers (supplier_id),
    invoice_number        VARCHAR(100)  NOT NULL,
    invoice_date          DATE          NOT NULL,
    interstate            BOOLEAN       NOT NULL DEFAULT FALSE,
    taxable_amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
    cgst_amount           NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount           NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount           NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount            NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    paid_amount           NUMERIC(14,2) NOT NULL DEFAULT 0,
    payment_status        VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    payment_due_date      DATE,
    notes                 TEXT,
    created_at            TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_wholesale_purchases_paid   CHECK (paid_amount >= 0),
    CONSTRAINT ck_wholesale_purchases_status CHECK (payment_status IN ('PENDING', 'PARTIAL', 'PAID'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_wholesale_purchases_supplier_invoice
    ON wholesale_purchases (supplier_id, LOWER(invoice_number));

CREATE TABLE IF NOT EXISTS wholesale_purchase_items (
    wholesale_purchase_item_id INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wholesale_purchase_id      INTEGER       NOT NULL REFERENCES wholesale_purchases (wholesale_purchase_id) ON DELETE CASCADE,
    wholesale_product_id       INTEGER       NOT NULL REFERENCES wholesale_products (wholesale_product_id),
    hsn_code                   VARCHAR(8),
    quantity                   NUMERIC(12,3) NOT NULL,
    purchase_rate              NUMERIC(12,2) NOT NULL,
    gst_pct                    NUMERIC(5,2)  NOT NULL,
    taxable_amount             NUMERIC(14,2) NOT NULL,
    cgst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount                 NUMERIC(14,2) NOT NULL,
    total_amount               NUMERIC(14,2) NOT NULL,
    CONSTRAINT ck_wholesale_purchase_items_qty  CHECK (quantity > 0),
    CONSTRAINT ck_wholesale_purchase_items_rate CHECK (purchase_rate >= 0)
);

CREATE INDEX IF NOT EXISTS idx_wholesale_purchase_items_purchase
    ON wholesale_purchase_items (wholesale_purchase_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_purchase_items_product
    ON wholesale_purchase_items (wholesale_product_id);
