-- Wholesale module V2: material info on wholesale products + quantity-based price rules.
-- Wholesale tables only; retail products/pricing are not touched.

ALTER TABLE wholesale_products ADD COLUMN IF NOT EXISTS material VARCHAR(200);

-- One row per quantity range ("slab") of a wholesale product.
--   min_quantity / max_quantity : inclusive range; max_quantity NULL = no upper limit ("100+").
--   price                       : selling price per unit, exclusive of GST.
--   gst_pct                     : NULL = use the product's GST %.
--   effective_from / to         : inclusive dates; NULL = open-ended.
-- Overlapping active rules (same product, overlapping quantity AND date range) are rejected by the service.
CREATE TABLE IF NOT EXISTS wholesale_product_price_rules (
    price_rule_id        INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wholesale_product_id INTEGER       NOT NULL REFERENCES wholesale_products (wholesale_product_id) ON DELETE CASCADE,
    min_quantity         NUMERIC(12,3) NOT NULL,
    max_quantity         NUMERIC(12,3),
    price                NUMERIC(12,2) NOT NULL,
    gst_pct              NUMERIC(5,2),
    is_active            BOOLEAN       NOT NULL DEFAULT TRUE,
    effective_from       DATE,
    effective_to         DATE,
    notes                VARCHAR(255),
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_wholesale_price_rules_min   CHECK (min_quantity > 0),
    CONSTRAINT ck_wholesale_price_rules_range CHECK (max_quantity IS NULL OR max_quantity >= min_quantity),
    CONSTRAINT ck_wholesale_price_rules_price CHECK (price >= 0),
    CONSTRAINT ck_wholesale_price_rules_gst   CHECK (gst_pct IS NULL OR (gst_pct >= 0 AND gst_pct <= 100)),
    CONSTRAINT ck_wholesale_price_rules_dates CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from)
);

CREATE INDEX IF NOT EXISTS idx_wholesale_price_rules_lookup
    ON wholesale_product_price_rules (wholesale_product_id, is_active, min_quantity);
