-- Wholesale module V3: wholesale customers (B2B parties for quotations, credit invoices, receipts, debit notes).
-- Deliberately separate from the retail `customers` table, which stays unchanged (bills, boutique, reports
-- and the Android app depend on its current shape).
--
-- Billing location (billing_address, city, state, pin_code) and shipping location are both stored.
-- When shipping_same_as_billing = TRUE the service copies the billing values into the shipping columns,
-- so documents can always read the delivery state (GST place of supply) from the shipping_* columns.

CREATE TABLE IF NOT EXISTS wholesale_customers (
    wholesale_customer_id    INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name            VARCHAR(150) NOT NULL,
    business_name            VARCHAR(200),
    customer_type            VARCHAR(20)  NOT NULL DEFAULT 'BUSINESS',
    gst_number               VARCHAR(15),
    phone                    VARCHAR(20),
    email                    VARCHAR(150),
    billing_address          TEXT,
    city                     VARCHAR(100),
    state_code               VARCHAR(2),
    state_name               VARCHAR(100),
    pin_code                 VARCHAR(6),
    shipping_same_as_billing BOOLEAN      NOT NULL DEFAULT TRUE,
    shipping_address         TEXT,
    shipping_city            VARCHAR(100),
    shipping_state_code      VARCHAR(2),
    shipping_state_name      VARCHAR(100),
    shipping_pin_code        VARCHAR(6),
    notes                    TEXT,
    is_active                BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_wholesale_customers_type CHECK (customer_type IN ('BUSINESS', 'DEALER', 'DISTRIBUTOR', 'RETAILER', 'OTHER')),
    CONSTRAINT ck_wholesale_customers_gst  CHECK (gst_number IS NULL OR gst_number ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$'),
    CONSTRAINT ck_wholesale_customers_pin  CHECK (pin_code IS NULL OR pin_code ~ '^[1-9][0-9]{5}$'),
    CONSTRAINT ck_wholesale_customers_ship_pin CHECK (shipping_pin_code IS NULL OR shipping_pin_code ~ '^[1-9][0-9]{5}$')
);

-- One customer per GSTIN (including inactive ones: reactivate instead of re-creating).
CREATE UNIQUE INDEX IF NOT EXISTS uq_wholesale_customers_gst
    ON wholesale_customers (gst_number) WHERE gst_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_wholesale_customers_name
    ON wholesale_customers (LOWER(customer_name));
CREATE INDEX IF NOT EXISTS idx_wholesale_customers_phone
    ON wholesale_customers (phone);
