-- Wholesale module V6: configurable document numbering + quotations.

-- ── Document numbering / defaults (one row per wholesale document type) ──────────────────────────
-- Number format: <prefix><sep><financial year><sep><zero-padded sequence>, e.g. QT/2025-26/0001.
-- Financial year runs April–March. When reset_each_financial_year = FALSE the sequence never resets.
CREATE TABLE IF NOT EXISTS wholesale_document_settings (
    doc_type                  VARCHAR(30)  PRIMARY KEY,
    prefix                    VARCHAR(20)  NOT NULL,
    separator                 VARCHAR(3)   NOT NULL DEFAULT '/',
    include_financial_year    BOOLEAN      NOT NULL DEFAULT TRUE,
    reset_each_financial_year BOOLEAN      NOT NULL DEFAULT TRUE,
    number_padding            INTEGER      NOT NULL DEFAULT 4,
    default_validity_days     INTEGER      NOT NULL DEFAULT 15,
    default_terms             TEXT,
    updated_at                TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_by                VARCHAR(100),
    CONSTRAINT ck_wholesale_doc_settings_type    CHECK (doc_type IN ('QUOTATION')),
    CONSTRAINT ck_wholesale_doc_settings_prefix  CHECK (prefix ~ '^[A-Za-z0-9-]{1,20}$'),
    CONSTRAINT ck_wholesale_doc_settings_sep     CHECK (separator IN ('/', '-', '')),
    CONSTRAINT ck_wholesale_doc_settings_pad     CHECK (number_padding BETWEEN 1 AND 8),
    CONSTRAINT ck_wholesale_doc_settings_valid   CHECK (default_validity_days BETWEEN 1 AND 365)
);

INSERT INTO wholesale_document_settings (doc_type, prefix, default_terms)
VALUES ('QUOTATION', 'QT', 'Prices are exclusive of GST unless stated. Quotation valid until the date shown. Goods once sold will not be taken back.')
ON CONFLICT (doc_type) DO NOTHING;

-- Last issued sequence per document type and period ('2025-26', or 'ALL' when not resetting yearly).
CREATE TABLE IF NOT EXISTS wholesale_document_counters (
    doc_type    VARCHAR(30) NOT NULL REFERENCES wholesale_document_settings (doc_type),
    period      VARCHAR(10) NOT NULL,
    last_number INTEGER     NOT NULL,
    PRIMARY KEY (doc_type, period),
    CONSTRAINT ck_wholesale_doc_counters_positive CHECK (last_number >= 0)
);

-- ── Quotations ───────────────────────────────────────────────────────────────────────────────────
-- Customer and firm details are SNAPSHOTS (copied when saved as draft and frozen when issued), so later
-- edits to the customer, business profile or price rules never change an existing quotation.
CREATE TABLE IF NOT EXISTS wholesale_quotations (
    quotation_id               INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_number           VARCHAR(40)   UNIQUE,              -- assigned on ISSUE; NULL while DRAFT
    status                     VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    quotation_date             DATE          NOT NULL,
    valid_until                DATE          NOT NULL,

    wholesale_customer_id      INTEGER       NOT NULL REFERENCES wholesale_customers (wholesale_customer_id),
    customer_name              VARCHAR(150)  NOT NULL,
    customer_business_name     VARCHAR(200),
    customer_gst_number        VARCHAR(15),
    customer_phone             VARCHAR(20),
    customer_email             VARCHAR(150),
    billing_address            TEXT,
    billing_city               VARCHAR(100),
    billing_state_code         VARCHAR(2),
    billing_state_name         VARCHAR(100),
    billing_pin_code           VARCHAR(6),
    shipping_address           TEXT,
    shipping_city              VARCHAR(100),
    shipping_state_code        VARCHAR(2),
    shipping_state_name        VARCHAR(100),
    shipping_pin_code          VARCHAR(6),

    firm_snapshot_json         TEXT          NOT NULL,            -- WholesaleDocumentProfile as JSON
    firm_state_code            VARCHAR(2)    NOT NULL,
    place_of_supply_state_code VARCHAR(2),
    interstate                 BOOLEAN       NOT NULL DEFAULT FALSE,

    gross_amount               NUMERIC(14,2) NOT NULL DEFAULT 0,  -- Σ qty × rate
    discount_amount            NUMERIC(14,2) NOT NULL DEFAULT 0,  -- Σ line discounts
    subtotal                   NUMERIC(14,2) NOT NULL DEFAULT 0,  -- Σ line taxable value
    other_charges_label        VARCHAR(60),
    other_charges_amount       NUMERIC(14,2) NOT NULL DEFAULT 0,  -- taxable value of other charges
    other_charges_gst_pct      NUMERIC(5,2)  NOT NULL DEFAULT 0,
    other_charges_gst_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
    cgst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount                 NUMERIC(14,2) NOT NULL DEFAULT 0,
    round_off                  NUMERIC(6,2)  NOT NULL DEFAULT 0,
    grand_total                NUMERIC(14,2) NOT NULL DEFAULT 0,

    notes                      TEXT,
    terms                      TEXT,
    duplicated_from_id         INTEGER       REFERENCES wholesale_quotations (quotation_id) ON DELETE SET NULL,
    cancel_reason              VARCHAR(255),
    created_at                 TIMESTAMP     NOT NULL DEFAULT NOW(),
    created_by                 VARCHAR(100),
    updated_at                 TIMESTAMP     NOT NULL DEFAULT NOW(),
    issued_at                  TIMESTAMP,
    issued_by                  VARCHAR(100),
    status_changed_at          TIMESTAMP,
    status_changed_by          VARCHAR(100),

    CONSTRAINT ck_wholesale_quotations_status CHECK (status IN ('DRAFT','ISSUED','ACCEPTED','REJECTED','EXPIRED','CONVERTED','CANCELLED')),
    CONSTRAINT ck_wholesale_quotations_validity CHECK (valid_until >= quotation_date),
    CONSTRAINT ck_wholesale_quotations_number CHECK (status = 'DRAFT' OR status = 'CANCELLED' OR quotation_number IS NOT NULL),
    CONSTRAINT ck_wholesale_quotations_other CHECK (other_charges_amount >= 0 AND other_charges_gst_pct BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS idx_wholesale_quotations_customer ON wholesale_quotations (wholesale_customer_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_quotations_status_date ON wholesale_quotations (status, quotation_date DESC);

-- Item rows keep the ACTUAL rate used. price_rule_id / rule_rate only record where it came from;
-- deleting or changing the rule never changes the item.
CREATE TABLE IF NOT EXISTS wholesale_quotation_items (
    quotation_item_id    INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id         INTEGER       NOT NULL REFERENCES wholesale_quotations (quotation_id) ON DELETE CASCADE,
    line_no              INTEGER       NOT NULL,
    wholesale_product_id INTEGER       NOT NULL REFERENCES wholesale_products (wholesale_product_id),
    price_rule_id        INTEGER       REFERENCES wholesale_product_price_rules (price_rule_id) ON DELETE SET NULL,
    item_name            VARCHAR(200)  NOT NULL,
    product_code         VARCHAR(50),
    hsn_code             VARCHAR(8),
    unit                 VARCHAR(20)   NOT NULL,
    description          VARCHAR(500),
    quantity             NUMERIC(12,3) NOT NULL,
    rate                 NUMERIC(12,2) NOT NULL,
    rate_source          VARCHAR(10)   NOT NULL,               -- RULE = slab price, MANUAL = user override
    rule_rate            NUMERIC(12,2),                        -- slab price at that time (if any)
    discount_pct         NUMERIC(5,2)  NOT NULL DEFAULT 0,
    gross_amount         NUMERIC(14,2) NOT NULL,
    discount_amount      NUMERIC(14,2) NOT NULL DEFAULT 0,
    taxable_amount       NUMERIC(14,2) NOT NULL,
    gst_pct              NUMERIC(5,2)  NOT NULL,
    cgst_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount           NUMERIC(14,2) NOT NULL,
    total_amount         NUMERIC(14,2) NOT NULL,
    CONSTRAINT uq_wholesale_quotation_items_line UNIQUE (quotation_id, line_no),
    CONSTRAINT ck_wholesale_quotation_items_qty  CHECK (quantity > 0),
    CONSTRAINT ck_wholesale_quotation_items_rate CHECK (rate >= 0),
    CONSTRAINT ck_wholesale_quotation_items_disc CHECK (discount_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_wholesale_quotation_items_gst  CHECK (gst_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_wholesale_quotation_items_src  CHECK (rate_source IN ('RULE', 'MANUAL'))
);

CREATE INDEX IF NOT EXISTS idx_wholesale_quotation_items_quotation ON wholesale_quotation_items (quotation_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_quotation_items_product ON wholesale_quotation_items (wholesale_product_id);
