-- Wholesale module V7: convert quotations into Sales Receipts (paid at sale) or Credit Notes (credit sale,
-- printed as "TAX INVOICE (CREDIT SALE)"). Wholesale only — the retail bills / invoice flow is untouched.

-- ── Numbering for the new document types ─────────────────────────────────────────────────────────
ALTER TABLE wholesale_document_settings DROP CONSTRAINT IF EXISTS ck_wholesale_doc_settings_type;
ALTER TABLE wholesale_document_settings
    ADD CONSTRAINT ck_wholesale_doc_settings_type CHECK (doc_type IN ('QUOTATION', 'SALES_RECEIPT', 'CREDIT_NOTE'));
ALTER TABLE wholesale_document_settings ADD COLUMN IF NOT EXISTS default_due_days INTEGER NOT NULL DEFAULT 30;
ALTER TABLE wholesale_document_settings DROP CONSTRAINT IF EXISTS ck_wholesale_doc_settings_due;
ALTER TABLE wholesale_document_settings
    ADD CONSTRAINT ck_wholesale_doc_settings_due CHECK (default_due_days BETWEEN 0 AND 365);

-- Defaults follow the requested style: SR-000001, CN-000001 (no financial year, continuous numbering).
INSERT INTO wholesale_document_settings (doc_type, prefix, separator, include_financial_year, reset_each_financial_year, number_padding, default_terms)
VALUES ('SALES_RECEIPT', 'SR', '-', FALSE, FALSE, 6, 'Goods once sold will not be taken back.'),
       ('CREDIT_NOTE',   'CN', '-', FALSE, FALSE, 6, 'Payment due by the date shown. Interest may be charged on overdue amounts.')
ON CONFLICT (doc_type) DO NOTHING;

-- ── Sales documents (created by converting a quotation) ──────────────────────────────────────────
-- All customer details, items, rates, GST and totals are COPIED from the quotation as it stood
-- (never re-priced). Letterhead / bank / UPI come from the business profile at conversion time.
CREATE TABLE IF NOT EXISTS wholesale_sales_documents (
    sales_document_id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type                   VARCHAR(20)   NOT NULL,
    document_number            VARCHAR(40)   NOT NULL UNIQUE,
    document_date              DATE          NOT NULL,
    status                     VARCHAR(20)   NOT NULL DEFAULT 'ISSUED',
    source_quotation_id        INTEGER       REFERENCES wholesale_quotations (quotation_id),

    wholesale_customer_id      INTEGER       NOT NULL REFERENCES wholesale_customers (wholesale_customer_id),
    customer_name              VARCHAR(150)  NOT NULL,
    customer_business_name     VARCHAR(200),
    customer_gst_number        VARCHAR(15),
    customer_phone             VARCHAR(20),
    customer_email             VARCHAR(150),
    billing_address            TEXT,
    billing_city               VARCHAR(100),
    billing_state_code         VARCHAR(2),
    billing_state_name         VARCHAR(100),
    billing_pin_code           VARCHAR(6),
    shipping_address           TEXT,
    shipping_city              VARCHAR(100),
    shipping_state_code        VARCHAR(2),
    shipping_state_name        VARCHAR(100),
    shipping_pin_code          VARCHAR(6),

    firm_snapshot_json         TEXT          NOT NULL,
    firm_state_code            VARCHAR(2)    NOT NULL,
    place_of_supply_state_code VARCHAR(2),
    interstate                 BOOLEAN       NOT NULL DEFAULT FALSE,

    gross_amount               NUMERIC(14,2) NOT NULL DEFAULT 0,
    discount_amount            NUMERIC(14,2) NOT NULL DEFAULT 0,
    subtotal                   NUMERIC(14,2) NOT NULL DEFAULT 0,
    other_charges_label        VARCHAR(60),
    other_charges_amount       NUMERIC(14,2) NOT NULL DEFAULT 0,
    other_charges_gst_pct      NUMERIC(5,2)  NOT NULL DEFAULT 0,
    other_charges_gst_amount   NUMERIC(14,2) NOT NULL DEFAULT 0,
    cgst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount                NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount                 NUMERIC(14,2) NOT NULL DEFAULT 0,
    round_off                  NUMERIC(6,2)  NOT NULL DEFAULT 0,
    grand_total                NUMERIC(14,2) NOT NULL DEFAULT 0,

    -- Payment: Sales Receipt = paid in full at sale; Credit Note = due later.
    payment_mode               VARCHAR(20),
    payment_reference          VARCHAR(100),
    amount_paid                NUMERIC(14,2) NOT NULL DEFAULT 0,
    payment_status             VARCHAR(10)   NOT NULL,
    due_date                   DATE,

    notes                      TEXT,
    terms                      TEXT,
    created_at                 TIMESTAMP     NOT NULL DEFAULT NOW(),
    created_by                 VARCHAR(100),
    converted_at               TIMESTAMP,
    converted_by               VARCHAR(100),
    updated_at                 TIMESTAMP     NOT NULL DEFAULT NOW(),
    cancelled_at               TIMESTAMP,
    cancelled_by               VARCHAR(100),
    cancel_reason              VARCHAR(255),

    CONSTRAINT ck_wholesale_sales_docs_type    CHECK (doc_type IN ('SALES_RECEIPT', 'CREDIT_NOTE')),
    CONSTRAINT ck_wholesale_sales_docs_status  CHECK (status IN ('ISSUED', 'CANCELLED')),
    CONSTRAINT ck_wholesale_sales_docs_payst   CHECK (payment_status IN ('PAID', 'PARTIAL', 'UNPAID')),
    CONSTRAINT ck_wholesale_sales_docs_mode    CHECK (payment_mode IS NULL OR payment_mode IN ('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE')),
    CONSTRAINT ck_wholesale_sales_docs_receipt CHECK (doc_type <> 'SALES_RECEIPT' OR payment_mode IS NOT NULL),
    CONSTRAINT ck_wholesale_sales_docs_credit  CHECK (doc_type <> 'CREDIT_NOTE' OR due_date IS NOT NULL),
    CONSTRAINT ck_wholesale_sales_docs_paid    CHECK (amount_paid >= 0)
);

CREATE INDEX IF NOT EXISTS idx_wholesale_sales_docs_quotation ON wholesale_sales_documents (source_quotation_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_sales_docs_customer  ON wholesale_sales_documents (wholesale_customer_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_sales_docs_type_date ON wholesale_sales_documents (doc_type, document_date DESC);

CREATE TABLE IF NOT EXISTS wholesale_sales_document_items (
    sales_document_item_id   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_document_id        INTEGER       NOT NULL REFERENCES wholesale_sales_documents (sales_document_id) ON DELETE CASCADE,
    line_no                  INTEGER       NOT NULL,
    source_quotation_item_id INTEGER       REFERENCES wholesale_quotation_items (quotation_item_id) ON DELETE SET NULL,
    wholesale_product_id     INTEGER       NOT NULL REFERENCES wholesale_products (wholesale_product_id),
    item_name                VARCHAR(200)  NOT NULL,
    product_code             VARCHAR(50),
    hsn_code                 VARCHAR(8),
    unit                     VARCHAR(20)   NOT NULL,
    description              VARCHAR(500),
    quantity                 NUMERIC(12,3) NOT NULL,
    rate                     NUMERIC(12,2) NOT NULL,
    rate_source              VARCHAR(10)   NOT NULL,
    discount_pct             NUMERIC(5,2)  NOT NULL DEFAULT 0,
    gross_amount             NUMERIC(14,2) NOT NULL,
    discount_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    taxable_amount           NUMERIC(14,2) NOT NULL,
    gst_pct                  NUMERIC(5,2)  NOT NULL,
    cgst_amount              NUMERIC(14,2) NOT NULL DEFAULT 0,
    sgst_amount              NUMERIC(14,2) NOT NULL DEFAULT 0,
    igst_amount              NUMERIC(14,2) NOT NULL DEFAULT 0,
    gst_amount               NUMERIC(14,2) NOT NULL,
    total_amount             NUMERIC(14,2) NOT NULL,
    CONSTRAINT uq_wholesale_sales_doc_items_line UNIQUE (sales_document_id, line_no),
    CONSTRAINT ck_wholesale_sales_doc_items_qty  CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_wholesale_sales_doc_items_doc ON wholesale_sales_document_items (sales_document_id);
CREATE INDEX IF NOT EXISTS idx_wholesale_sales_doc_items_product ON wholesale_sales_document_items (wholesale_product_id);
