-- Wholesale module V8: full Sales Receipt module — drafts, payment tracking, payment history.
-- Applies to both wholesale sales document types (Sales Receipt and Credit Note). Retail bills untouched.
--
-- Lifecycle (status):  DRAFT ─issue─▶ ISSUED ─payment─▶ PARTIALLY_PAID ─payment─▶ PAID
--                        └──────────────▶ CANCELLED ◀────────────┴──────────────────┘
-- payment_status (PAID / PARTIAL / UNPAID) is kept in step for existing readers.

-- ── Status values ────────────────────────────────────────────────────────────────────────────────
ALTER TABLE wholesale_sales_documents DROP CONSTRAINT IF EXISTS ck_wholesale_sales_docs_status;

-- Existing (Phase 6) rows: ISSUED + PAID -> PAID, ISSUED + PARTIAL -> PARTIALLY_PAID; ISSUED + UNPAID stays ISSUED.
UPDATE wholesale_sales_documents SET status = 'PAID'           WHERE status = 'ISSUED' AND payment_status = 'PAID';
UPDATE wholesale_sales_documents SET status = 'PARTIALLY_PAID' WHERE status = 'ISSUED' AND payment_status = 'PARTIAL';

ALTER TABLE wholesale_sales_documents
    ADD CONSTRAINT ck_wholesale_sales_docs_status CHECK (status IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED'));

-- ── Drafts have no number yet ────────────────────────────────────────────────────────────────────
ALTER TABLE wholesale_sales_documents ALTER COLUMN document_number DROP NOT NULL;
ALTER TABLE wholesale_sales_documents DROP CONSTRAINT IF EXISTS ck_wholesale_sales_docs_number;
ALTER TABLE wholesale_sales_documents
    ADD CONSTRAINT ck_wholesale_sales_docs_number CHECK (status IN ('DRAFT', 'CANCELLED') OR document_number IS NOT NULL);

-- Payment method now lives on each payment; the document column shows the latest method (may be empty).
ALTER TABLE wholesale_sales_documents DROP CONSTRAINT IF EXISTS ck_wholesale_sales_docs_receipt;

ALTER TABLE wholesale_sales_documents ADD COLUMN IF NOT EXISTS issued_at TIMESTAMP;
ALTER TABLE wholesale_sales_documents ADD COLUMN IF NOT EXISTS issued_by VARCHAR(100);
UPDATE wholesale_sales_documents SET issued_at = COALESCE(converted_at, created_at), issued_by = COALESCE(converted_by, created_by)
 WHERE issued_at IS NULL AND status <> 'DRAFT';

ALTER TABLE wholesale_sales_documents DROP CONSTRAINT IF EXISTS ck_wholesale_sales_docs_paid_le_total;
ALTER TABLE wholesale_sales_documents
    ADD CONSTRAINT ck_wholesale_sales_docs_paid_le_total CHECK (amount_paid <= grand_total);

-- ── Payment history ──────────────────────────────────────────────────────────────────────────────
-- Payments are never deleted; mistakes are VOIDED (with a reason) so the history stays auditable.
CREATE TABLE IF NOT EXISTS wholesale_sales_payments (
    payment_id        INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_document_id INTEGER       NOT NULL REFERENCES wholesale_sales_documents (sales_document_id) ON DELETE CASCADE,
    payment_date      DATE          NOT NULL,
    amount            NUMERIC(14,2) NOT NULL,
    payment_mode      VARCHAR(20)   NOT NULL,
    reference         VARCHAR(100),
    notes             VARCHAR(255),
    status            VARCHAR(10)   NOT NULL DEFAULT 'RECORDED',
    created_at        TIMESTAMP     NOT NULL DEFAULT NOW(),
    created_by        VARCHAR(100),
    voided_at         TIMESTAMP,
    voided_by         VARCHAR(100),
    void_reason       VARCHAR(255),
    CONSTRAINT ck_wholesale_sales_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_wholesale_sales_payments_mode   CHECK (payment_mode IN ('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE')),
    CONSTRAINT ck_wholesale_sales_payments_status CHECK (status IN ('RECORDED', 'VOIDED'))
);

CREATE INDEX IF NOT EXISTS idx_wholesale_sales_payments_doc ON wholesale_sales_payments (sales_document_id);

-- Backfill: Phase 6 receipts were paid in full at conversion; record that as their first payment.
INSERT INTO wholesale_sales_payments (sales_document_id, payment_date, amount, payment_mode, reference, created_at, created_by)
SELECT d.sales_document_id, d.document_date, d.amount_paid, d.payment_mode, d.payment_reference, d.created_at, d.created_by
  FROM wholesale_sales_documents d
 WHERE d.amount_paid > 0 AND d.payment_mode IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM wholesale_sales_payments p WHERE p.sales_document_id = d.sales_document_id);

CREATE INDEX IF NOT EXISTS idx_wholesale_sales_docs_status ON wholesale_sales_documents (status, document_date DESC);
